name: "Translating Bruno's DE VMBRIS IDEARVM"
baseurl: '/de-umbris-idearum'
description: "Translation of Giodarno Bruno's DE VMBRIS IDEARVM ('On the Shadows of Ideas')"
paginate: 10
excludes:
  - Rakefile
markdown: rdiscount
pygments: true
permalink: pretty
